# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210706_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.IntegerField(default=1000),
        ),
    ]
